spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/satu
    username: postgres
    password: HtkBbx51087#
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop
    show-sql: true
server:
  error:
    include-stacktrace: never
  port: 8081

app:
  config:
    company: OBS Financial Solutions Pte. Ltd.
    client: SampleCrudClient


